### ISSUE TITLE
Creep path avoids roads on penultimate step in addition to final

### ISSUE THREAD

**Issue by justonhart** [justonhart/Thoughtwave#11]
Instead of moving off roads in the last step of movement, the creep will try to move off road in the second-to-last step, leading to lost ticks from movement fatigue.

![image](https://user-images.githubusercontent.com/17937624/159526820-e7d0e122-8a73-4fc2-b1be-9d976e34835f.png)

**Comment by lipkam** [comment]
This is not necessarily two steps. Sometimes it happens earlier and sometimes not at all. This seems to be caused by the "reusePath" mechanism. Instead of calling another "moveTo" method when stuck, I will simply set the default options and delete the serializedPath variable set by moveTo.

**Comment by lipkam** [comment]
Well this is rather difficult to "fix". The reason why the creep moved off the road is because that tile is exactly 3 tiles (range of action) away from the destination. If the creep moved on the road for one more step it would stop traveling and start the requested action.  In many cases the creep can find a path with only one more step but if the target is directly diagonally from the creep then it will have to move twice. The only way to avoid that is to instead go towards the target and then queue up another travelTo command to moveOff the road.

**Comment by lipkam** [comment]
Wenn es nicht diagonal ist sieht es wie folgt aus: 
<img width="142" alt="image" src="https://user-images.githubusercontent.com/74310778/159697884-38a5c172-9eb8-4b05-b850-6b8f17ad9315.png">

**Comment by lipkam** [comment]
Hier nochmal die varianten:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/74310778/159698953-372f31a1-a1a4-4303-8bec-2549f75fa5e8.png">

<img width="267" alt="image" src="https://user-images.githubusercontent.com/74310778/159699062-069ef32e-ce2b-4b86-a603-44f9235e5f9e.png">

**Comment by justonhart** [comment]
I see. So this is something that really needs to be fixed at a creep level, as opposed to Pathing.
